version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/Extensions"
    update_schedule: "live"
    target_branch: "master"
    default_labels:
      - "dependencies"
      - "dependabot"